import { Language } from '../types';

const strings: Record<Language, Record<string, string>> = {
    tr: {
        appTitle: 'Akvaryum Su Kalitesi Paneli',
        dashboard: 'Pano',
        information: 'Bilgi',
        reports: 'Raporlar',
        settings: 'Ayarlar',
        help: 'Yardım',
        controlPanel: 'Kontrol Paneli',
        activeAlarms: 'Aktif Alarmlar',
        allSafe: 'Tüm değerler güvenli aralıkta.',
        menu: 'Menü',
        theme: 'Görünüm Teması',
        themeDescription: 'Uygulamanın genel görünümünü seçin.',
        lightTheme: 'Açık Tema',
        darkTheme: 'Koyu Tema',
        language: 'Dil',
        languageDescription: 'Uygulama dilini seçin.',
        quickActions: 'Hızlı İşlemler',
        lastFeeding: 'Son Yemleme',
        feedNow: 'Yem Atıldı',
        noFeedingLogged: 'Henüz yemleme kaydedilmedi.',
        lastFilterMaintenance: 'Filtre Bakımı',
        logMaintenance: 'Bakım Kaydet',
        noMaintenanceLogged: 'Henüz bakım kaydedilmedi.',
        notes: 'Notlar',
        feedingLogged: 'Yemleme yapıldı.',
        maintenanceLogged: 'Filtre bakımı yapıldı',
        filterNotesPrompt: 'Filtre bakımı ile ilgili notlarınızı girin:',
        filterNotesDefault: 'Filtre süngerleri temizlendi, aktif karbon değiştirildi.',
        edit: 'Düzenle',
        save: 'Kaydet',
        cancel: 'İptal',
        deleteFish: 'Bu balığı sil',
        addFish: 'Yeni Balık Ekle',
        filterMaintenance: 'Filtre Bakım Yönetimi',
        filterMedia: 'Filtre Malzemeleri',
        lastChanged: 'Son Değişim',
        nextChange: 'Sonraki Değişim',
        status: 'Durum',
        consequence: 'Sonuçları',
        markAsChanged: 'Değiştirildi Olarak İşaretle',
        close: 'Kapat',
        statusGood: 'İyi',
        statusSoon: 'Değişim Yaklaşıyor',
        statusOverdue: 'DEĞİŞİM ZAMANI GELDİ!',
        filterMediumChanged: 'filtre malzemesi değiştirildi.',
        changeIntervalDaysLabel: 'Değişim Aralığı (Gün)',
        addNewMedium: 'Yeni Malzeme Ekle',
        selectMediumToAdd: 'Eklenecek Malzemeyi Seçin...',
        add: 'Ekle',
        categoryMechanical: 'Mekanik Malzemeler',
        categoryBiological: 'Biyolojik Malzemeler',
        categoryChemical: 'Kimyasal Malzemeler',
        categoryExtra: 'Ekstra Malzemeler',
        reportsToday: 'Bugün',
        reportsThisWeek: 'Bu Hafta',
        reportsThisMonth: 'Bu Ay',
        reportsOlder: 'Daha Eski',
    },
    en: {
        appTitle: 'Aquarium Water Quality Panel',
        dashboard: 'Dashboard',
        information: 'Information',
        reports: 'Reports',
        settings: 'Settings',
        help: 'Help',
        controlPanel: 'Control Panel',
        activeAlarms: 'Active Alarms',
        allSafe: 'All parameters are in safe range.',
        menu: 'Menu',
        theme: 'Appearance Theme',
        themeDescription: 'Choose the overall look of the application.',
        lightTheme: 'Light Theme',
        darkTheme: 'Dark Theme',
        language: 'Language',
        languageDescription: 'Choose the application language.',
        quickActions: 'Quick Actions',
        lastFeeding: 'Last Feeding',
        feedNow: 'Feed Now',
        noFeedingLogged: 'No feeding logged yet.',
        lastFilterMaintenance: 'Filter Maintenance',
        logMaintenance: 'Log Maintenance',
        noMaintenanceLogged: 'No maintenance logged yet.',
        notes: 'Notes',
        feedingLogged: 'Feeding logged.',
        maintenanceLogged: 'Filter maintenance logged',
        filterNotesPrompt: 'Enter your notes for the filter maintenance:',
        filterNotesDefault: 'Cleaned filter sponges, replaced activated carbon.',
        edit: 'Edit',
        save: 'Save',
        cancel: 'Cancel',
        deleteFish: 'Delete this fish',
        addFish: 'Add New Fish',
        filterMaintenance: 'Filter Maintenance Management',
        filterMedia: 'Filter Media',
        lastChanged: 'Last Changed',
        nextChange: 'Next Change',
        status: 'Status',
        consequence: 'Consequences',
        markAsChanged: 'Mark as Changed',
        close: 'Close',
        statusGood: 'Good',
        statusSoon: 'Change Soon',
        statusOverdue: 'OVERDUE!',
        filterMediumChanged: 'filter medium changed.',
        changeIntervalDaysLabel: 'Change Interval (Days)',
        addNewMedium: 'Add New Medium',
        selectMediumToAdd: 'Select medium to add...',
        add: 'Add',
        categoryMechanical: 'Mechanical Media',
        categoryBiological: 'Biological Media',
        categoryChemical: 'Chemical Media',
        categoryExtra: 'Extra Media',
        reportsToday: 'Today',
        reportsThisWeek: 'This Week',
        reportsThisMonth: 'This Month',
        reportsOlder: 'Older',
    }
};

export type TranslationFunction = (key: keyof typeof strings.tr) => string;

export const useLocalization = (lang: Language): TranslationFunction => {
    return (key: keyof typeof strings.tr): string => {
        return strings[lang][key] || strings['tr'][key];
    };
};